[Modify] workflow

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -31,10 +31,9 @@ inputs:
     description: "Path to RootFS-overlay directory"
     required: false
 
-  verbose_log:
-    description: "Emit verbose (not omitted) build log from Buildroot. (NOTE: Buildroot will emit huge log)"
+  buildroot_log_path:
+    description: "Buildroot log output path"
     required: false
-    default: false
 
 runs:
   using: "composite"
@@ -90,12 +89,12 @@ runs:
           echo "rootfs_overlay_dir=$rootfsOverlayDir" >> "$GITHUB_OUTPUT"
         fi
 
-        if [ "${{ inputs.verbose_log }}" = "true" ]; then
-          echo "verbose log output enabled"
-          echo "verbose_log=true" >> "$GITHUB_OUTPUT"
-        else
-          echo "verbose log output disabled"
-          echo "verbose_log=false" >> "$GITHUB_OUTPUT"
+        if [ -n "${{ inputs.buildroot_log_path }}" ]; then
+          echo "has_buildroot_log_path=true" >> "$GITHUB_OUTPUT"
+
+          buildrootLogPath=`realpath "${{ inputs.buildroot_log_path }}"`
+          echo "buildroot log output path: $buildrootLogPath"
+          echo "buildroot_log_path=$buildrootLogPath" >> "$GITHUB_OUTPUT"
         fi
 
         outputAbsPath=`realpath -m "${{ inputs.output_path }}"`
@@ -218,13 +217,19 @@ runs:
     - name: build Raspberry Pi image
       shell: bash
       run: |
-        if [ "${{ steps.args.outputs.verbose_log }}" = "true" ]; then
-          logFilter=""
+        if [ "${{ steps.args.outputs.has_buildroot_log_path }}" = "true" ]; then
+          logDestination="${{ steps.args.outputs.buildroot_log_path }}"
         else
-          logFilter="sed -rn '/^\x1B\[7m>>> /p'"
+          logDestination="/dev/null"
         fi
-        command="make O=/dist"
-        docker exec ${{ steps.br_container.outputs.container_id }} $command | eval $logFilter
+        echo "Build Raspberry Pi image..."
+        docker exec ${{ steps.br_container.outputs.container_id }} make O=/dist > $logDestination 2>&1
+        if [ $? -eq 0 ]; then
+          echo "Finished."
+        else
+          echo "Build failed. if you specified option buildroot_log_path, build log will be saved to there."
+          exit 1
+        fi
     - name: take out built raspberry pi image
       shell: bash
       working-directory: ${{ github.action_path }}
